[package]
name = "tax-service"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = {version = "1.49", features = ["full"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
csv = "1.4"
rayon = "1.11"